### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by nebnes** [mapnificent/mapnificent_generator#2]
Hello, 
I am newbie with go. 
When I run mapnificent_generator. I get this error:

```
2016/05/22 12:43:56 discoverGtfsPaths: in.zip
gtfs - 2016/05/22 12:43:56 in.zip
gtfs - 2016/05/22 12:43:56 Started loading in.zip
gtfs - 2016/05/22 12:43:56 calendar_dates.txt
gtfs - 2016/05/22 12:43:56 calendar_dates.txt
gtfs - 2016/05/22 12:43:56 calendar_dates.txt
gtfs - 2016/05/22 12:43:56 calendar_dates.txt
gtfs - 2016/05/22 12:43:56 calendar_dates.txt
gtfs - 2016/05/22 12:43:56 calendar_dates.txt
gtfs - 2016/05/22 12:43:56 calendar_dates.txt
gtfs - 2016/05/22 12:43:56 calendar_dates.txt
gtfs - 2016/05/22 12:43:56 agency.txt
gtfs - 2016/05/22 12:43:56 stops.txt
gtfs - 2016/05/22 12:43:56 routes.txt
gtfs - 2016/05/22 12:43:56 trips.txt
gtfs - 2016/05/22 12:43:57 stop_times.txt
gtfs - 2016/05/22 12:44:04 calendar.txt
gtfs - 2016/05/22 12:44:04 calendar_dates.txt
gtfs - 2016/05/22 12:44:04 shapes.txt
gtfs - 2016/05/22 12:44:04 Bench 'Trips calculations' took: 5.5076 ms - result: yes
gtfs - 2016/05/22 12:44:04 Agency count 1
gtfs - 2016/05/22 12:44:04 Stops count 3451
gtfs - 2016/05/22 12:44:04 Routes count 1
gtfs - 2016/05/22 12:44:04 Trip count 23133
gtfs - 2016/05/22 12:44:04 StopTimes count 632626
gtfs - 2016/05/22 12:44:04 Shapes count 253
gtfs - 2016/05/22 12:44:04 Calendars count 32
gtfs - 2016/05/22 12:44:04 CalendarDates count 27
gtfs - 2016/05/22 12:44:04 Tranfers count 0
gtfs - 2016/05/22 12:44:04 FrequenciesCount count 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4034b5]

goroutine 1 [running]:
panic(0x5a7300, 0xc082002090)
        C:/Go/src/runtime/panic.go:481 +0x3f4
main.GetTripHash(0xc0821958c0, 0x0, 0x0)
        D:/LAB/GO_workspace/src/github.com/mapnificent/mapnificent_generator/mapnificent.go:199 +0x105
main.GetNetwork(0xc082050420, 0x3)
        D:/LAB/GO_workspace/src/github.com/mapnificent/mapnificent_generator/mapnificent.go:115 +0x2e3
main.main()
        D:/LAB/GO_workspace/src/github.com/mapnificent/mapnificent_generator/mapnificent.go:277 +0x7ea

```

I have the same result on win10 and osx with different input files

**Comment by stefanw** [comment]
I've done a lot of updates to the code. Could you check again now? Also the GTFS file in question would help to narrow down the issue.

**Comment by stefanw** [comment]
Closing this because code has changed a lot.
